version: '3.6'

services:
  metabase-app:
    container_name: metabase-app
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase-db
      MB_DB_PORT: 5432
      MB_DB_USER: example
      MB_DB_PASS: example
      MB_DB_HOST: metabase-db

  metabase-db:
    image: postgres
    container_name: metabase-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: metabase-db
    ports:
      - 5432:5432
